# Generated by Django 2.2.5 on 2019-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20191215_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Person's first name"),
        ),
    ]
