# Generated by Django 2.2.5 on 2019-12-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20191215_0432'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
        migrations.AlterModelTable(
            name='musician',
            table='Musician',
        ),
    ]
