# Generated by Django 2.2.5 on 2019-12-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20191226_0824'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
    ]
